# Generated by Django 3.2.3 on 2021-05-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
